version: "3.3"
services:
  gerenciadorescolar-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Servidor."
    ports:
      - "5470:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gescolar_network

  gerenciadorescolar-api:
    container_name: gerenciadorescolar_api
    image: gerenciadorescolar-api
    ports:
      - 8095:80
    networks:
      - gescolar_network
    depends_on:
      - gerenciadorescolar-db

  gerenciadorescolar-web:
    container_name: gerenciadorescolar_web
    image: gerenciadorescolar-web
    ports:
      - 8080:80
    networks:
      - gescolar_network
    depends_on:
      - gerenciadorescolar-api

networks:
  gescolar_network:
    driver: bridge

volumes:
  db_data:
    driver: local
